name: Build Noctis (Fabric 1.21.4)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Ensure gradle-wrapper.jar is readable
  run: chmod 644 gradle/wrapper/gradle-wrapper.jar

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: noctis-fabric-jar
          path: build/libs/*.jar
