name: Build Noctis (Fabric 1.21.4)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Build WITHOUT gradlew (no wrapper needed)
      - name: Build with Gradle (no wrapper)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          build-root-directory: .
          arguments: build

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: noctis-fabric-jar
          path: build/libs/*.jar
